name: shake_gesture
description: Provides a widget to detect shake gestures. It allows you to easily add shake detection to your Flutter app on Android and iOS.
version: 1.0.5
homepage: https://github.com/tpucci/shake_gesture
repository: https://github.com/tpucci/shake_gesture

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: shake_gesture_android
      ios:
        default_package: shake_gesture_ios

dependencies:
  flutter:
    sdk: flutter
  shake_gesture_android: 1.1.2
  shake_gesture_ios: 1.0.2
  shake_gesture_platform_interface: 1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ">=5.0.0 <7.0.0"
