name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - tpucci
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Scope
      description: What platforms are concerned?
      options:
        - Android 🤖
        - iOS 🍎
        - Both!
      default: 0
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: Please copy and paste the output of `flutter pub deps | grep "shake"`. This will be automatically formatted into code, so no need for backticks.
      render: shell
