name: shake_gesture_ios
description: iOS implementation of the shake_gesture plugin
version: 1.0.2
homepage: https://github.com/tpucci/shake_gesture
repository: https://github.com/tpucci/shake_gesture

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    implements: shake_gesture
    platforms:
      ios:
        pluginClass: ShakeGesturePlugin
        dartPluginClass: ShakeGestureIOS

dependencies:
  flutter:
    sdk: flutter
  shake_gesture_platform_interface: 1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.0.0
